name: Python Scheduled Script

on:
  schedule:
  - cron: "* * * * *"



jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Execute Python script
        run: python scraper.py
      - name: Commit Files
        run: |
          git config --local user.name ChrisPrice03
          git config --local user.email squacknog@gmail.com
          git add --all
          git push origin main
