name: Python Scheduled Script

on:
  schedule:
  - cron: "* * * * *"



jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Execute Python script
        run: python scraper.py
      - name: Checkout repo
        run: actions/checkout@v2
      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Commit Files
        run: |
          git config --local user.name ChrisPrice03
          git config --local user.email squacknog@gmail.com
          git add --all
          git push origin main
